from __future__ import annotations

import logging
from collections import Counter, deque
from pathlib import Path

import torch
import torch.nn.functional as F
from miditok import REMI, TokSequence
from torch import Tensor

from model import KVCache, MusicTransformer, get_device
from scripts.tokenize_midi import (
    UNCONDITIONAL_COMPOSER,
    ComposerREMI,
    composer_vocab_token,
)

CHECKPOINT_PATH = Path("checkpoints/model_best.pt")
TOKENIZER_PATH = Path("data/processed/tokenizer.json")
OUTPUT_PATH = Path("data/processed/output.mid")

COMPOSER = "Frédéric Chopin"
GENERATION_LENGTH = 1024
TEMPERATURE = 0.8
# Nucleus sampling only; top-k truncation is disabled by default.
TOP_K = 0
TOP_P = 0.9
CFG_SCALE = 1.2
REPETITION_PENALTY = 1.02
# Rest/TimeShift loops are the "silent bar" failure mode, so they are penalized
# harder than pitches and the penalty escalates with each recent occurrence.
TIME_REPETITION_PENALTY = 1.0
MAX_TIME_PENALTY_EXPONENT = 4.0
REPETITION_WINDOW = 80
STUCK_LOOKBACK = 64
NGRAM_MIN_LEN = 4
NGRAM_MAX_LEN = 8
TEMPERATURE_BOOST = 0.2
# The training chunks never contained EOS, so its logit is unreliable early on.
MIN_NEW_TOKENS = 64

TIME_PREFIXES = ("TimeShift", "Rest")

logger = logging.getLogger(__name__)


class TokenCategories:
    def __init__(self, tokenizer: REMI, device: torch.device) -> None:
        pitch: list[int] = []
        structural: list[int] = []
        time_shift: list[int] = []
        forbidden: list[int] = []
        for token, token_id in tokenizer.vocab.items():
            prefix = token.split("_")[0]
            if prefix in ("Pitch", "PitchDrum"):
                pitch.append(token_id)
            elif prefix in ("Bar", "Position"):
                structural.append(token_id)
            elif prefix in TIME_PREFIXES:
                time_shift.append(token_id)
            elif prefix in ("PAD", "BOS", "MASK", "Composer"):
                forbidden.append(token_id)

        vocab_size = len(tokenizer)
        self.eos_token_id = int(tokenizer.vocab["EOS_None"])
        self.pitch_ids = torch.tensor(pitch, dtype=torch.long, device=device)
        self.structural_ids = torch.tensor(structural, dtype=torch.long, device=device)
        self.time_ids = torch.tensor(time_shift, dtype=torch.long, device=device)
        self.forbidden_ids = torch.tensor(forbidden, dtype=torch.long, device=device)

        self.is_pitch = torch.zeros(vocab_size, dtype=torch.bool, device=device)
        self.is_pitch[self.pitch_ids] = True
        self.is_structural = torch.zeros(vocab_size, dtype=torch.bool, device=device)
        self.is_structural[self.structural_ids] = True
        self.is_time = torch.zeros(vocab_size, dtype=torch.bool, device=device)
        self.is_time[self.time_ids] = True


def load_model(checkpoint_path: Path, device: torch.device) -> MusicTransformer:
    checkpoint = torch.load(checkpoint_path, map_location=device)
    vocab_size = int(checkpoint["vocab_size"])
    model = MusicTransformer(vocab_size=vocab_size).to(device)
    state_dict = checkpoint["model_state_dict"]
    cleaned = {
        (key[len("_orig_mod.") :] if key.startswith("_orig_mod.") else key): value
        for key, value in state_dict.items()
    }

    try:
        model.load_state_dict(cleaned)
    except RuntimeError as exc:
        raise RuntimeError(
            f"Checkpoint {checkpoint_path} does not match the current architecture "
            "(RMSNorm + SwiGLU + KV-cache). Checkpoints trained before this change "
            "must be regenerated by re-running train.py."
        ) from exc
    model.eval()
    logger.info(
        "Loaded model from %s | vocab_size=%d | %.2fM params",
        checkpoint_path,
        vocab_size,
        model.get_num_params(),
    )
    return model


def list_composer_tokens(tokenizer: REMI) -> list[str]:
    return sorted(token for token in tokenizer.vocab if token.startswith("Composer_"))


def resolve_composer_token(tokenizer: REMI, composer: str) -> str:
    token = composer_vocab_token(composer)
    if token in tokenizer.vocab:
        return token

    available = list_composer_tokens(tokenizer)
    raise KeyError(
        f"Composer token {token!r} missing from tokenizer. Available: {available}"
    )


def pick_start_token(tokenizer: REMI, composer: str) -> int:
    token = resolve_composer_token(tokenizer, composer)
    start_token = tokenizer[token]
    logger.info("Using composer seed %s (id=%d)", token, start_token)
    return start_token


def pick_unconditional_token(tokenizer: REMI) -> int | None:
    token = composer_vocab_token(UNCONDITIONAL_COMPOSER)
    if token not in tokenizer.vocab:
        return None
    return int(tokenizer.vocab[token])


def apply_repetition_penalty(
    logits: Tensor,
    window: deque[int],
    categories: TokenCategories,
    pitch_penalty: float,
    time_penalty: float,
) -> None:
    if not window:
        return

    counts = Counter(window)
    recent_ids = torch.tensor(sorted(counts), dtype=torch.long, device=logits.device)
    occurrences = torch.tensor(
        [float(counts[int(token_id)]) for token_id in recent_ids],
        device=logits.device,
    )

    divisor = torch.ones_like(occurrences)
    if pitch_penalty > 1.0:
        divisor[categories.is_pitch[recent_ids]] = pitch_penalty
    if time_penalty > 1.0:
        is_time = categories.is_time[recent_ids]
        exponent = occurrences[is_time].clamp(max=MAX_TIME_PENALTY_EXPONENT)
        divisor[is_time] = time_penalty**exponent

    scores = logits[recent_ids]
    logits[recent_ids] = torch.where(
        scores > 0, scores / divisor, scores * divisor
    )


def top_k_top_p_filter(logits: Tensor, top_k: int, top_p: float) -> Tensor:
    filtered = logits.clone()

    if top_k > 0:
        top_k = min(top_k, filtered.shape[-1])
        kth_value = torch.topk(filtered, top_k).values[-1]
        filtered[filtered < kth_value] = float("-inf")

    if 0.0 < top_p < 1.0:
        sorted_logits, sorted_indices = torch.sort(filtered, descending=True)
        cumulative_probs = F.softmax(sorted_logits, dim=-1).cumsum(dim=-1)
        remove_sorted = cumulative_probs > top_p
        remove_sorted[1:] = remove_sorted[:-1].clone()
        remove_sorted[0] = False
        remove_indices = sorted_indices[remove_sorted]
        filtered[remove_indices] = float("-inf")

    return filtered


def is_stuck(window: deque[int]) -> bool:
    """Detect repeating n-grams (length 4-8) in the recent token window."""
    if len(window) < NGRAM_MIN_LEN * 2:
        return False

    tokens = list(window)
    for ngram_len in range(NGRAM_MIN_LEN, NGRAM_MAX_LEN + 1):
        if len(tokens) < ngram_len * 2:
            continue
        tail = tokens[-ngram_len:]
        prev = tokens[-(ngram_len * 2) : -ngram_len]
        if tail == prev:
            return True
    return False


@torch.no_grad()
def generate(
    model: MusicTransformer,
    tokenizer: REMI,
    device: torch.device,
    length: int,
    temperature: float = TEMPERATURE,
    top_k: int = TOP_K,
    composer: str = COMPOSER,
    top_p: float = TOP_P,
    repetition_penalty: float = REPETITION_PENALTY,
    repetition_window: int = REPETITION_WINDOW,
    time_repetition_penalty: float = TIME_REPETITION_PENALTY,
    cfg_scale: float = CFG_SCALE,
) -> list[int]:
    categories = TokenCategories(tokenizer, device)
    start_token = pick_start_token(tokenizer, composer)

    uncond_token = pick_unconditional_token(tokenizer)
    if cfg_scale != 1.0 and uncond_token is None:
        logger.warning(
            "Tokenizer has no %s token, disabling classifier-free guidance. "
            "Re-run scripts/tokenize_midi.py to rebuild the vocabulary.",
            composer_vocab_token(UNCONDITIONAL_COMPOSER),
        )
        cfg_scale = 1.0
    use_cfg = cfg_scale != 1.0

    # The rotary cache is sized to max_seq_len, so generation cannot outrun it.
    max_tokens = min(length, model.max_seq_len)
    if max_tokens < length:
        logger.warning(
            "Requested %d tokens but max_seq_len=%d; truncating the request",
            length,
            model.max_seq_len,
        )

    batch_size = 2 if use_cfg else 1
    generated = torch.empty((batch_size, max_tokens), device=device, dtype=torch.long)
    generated[0, 0] = start_token
    if use_cfg:
        assert uncond_token is not None
        generated[1, 0] = uncond_token
        logger.info(
            "Classifier-free guidance scale=%.2f (uncond id=%d)",
            cfg_scale,
            uncond_token,
        )

    penalty_window: deque[int] = deque([start_token], maxlen=repetition_window)
    stuck_window: deque[int] = deque([start_token], maxlen=STUCK_LOOKBACK)

    past_key_values: list[KVCache | None] | None = None
    log_every = max(max_tokens // 10, 1)
    total_tokens = max_tokens

    step = 1
    while step < max_tokens:
        # The cache is never trimmed: the first pass consumes the whole prefix and
        # every later pass feeds exactly one new token on top of the kept cache.
        context = generated[:, :step] if past_key_values is None else generated[:, step - 1 : step]

        logits, past_key_values = model(
            context,
            past_key_values=past_key_values,
            use_cache=True,
        )

        if use_cfg:
            conditional = logits[0, -1, :].float()
            unconditional = logits[1, -1, :].float()
            next_logits = unconditional + cfg_scale * (conditional - unconditional)
        else:
            next_logits = logits[0, -1, :].float()
        assert next_logits.ndim == 1, f"Got {next_logits.shape}"

        next_logits[categories.forbidden_ids] = float("-inf")
        if step < MIN_NEW_TOKENS:
            next_logits[categories.eos_token_id] = float("-inf")
        apply_repetition_penalty(
            next_logits,
            penalty_window,
            categories,
            repetition_penalty,
            time_repetition_penalty,
        )

        effective_temperature = temperature
        if is_stuck(stuck_window):
            effective_temperature += TEMPERATURE_BOOST
        next_logits = next_logits / effective_temperature

        structural_scores = next_logits[categories.structural_ids].clone()
        filtered = top_k_top_p_filter(next_logits, top_k, top_p)
        if torch.isinf(filtered).all():
            filtered[categories.structural_ids] = structural_scores

        probs = F.softmax(filtered, dim=-1)
        next_token = int(torch.multinomial(probs, num_samples=1).item())

        if next_token == categories.eos_token_id:
            logger.info("EOS sampled at step %d, stopping", step)
            total_tokens = step
            break

        generated[:, step] = next_token
        penalty_window.append(next_token)
        stuck_window.append(next_token)
        step += 1

        if step % log_every == 0 or step == max_tokens:
            logger.info("Generated %d/%d tokens (id=%d)", step, max_tokens, next_token)

    result = generated[0, :total_tokens].tolist()
    assert len(result) == total_tokens, f"Got {len(result)}"
    return result


def tokens_to_midi_file(
    tokenizer: REMI,
    token_ids: list[int],
    output_path: Path,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    composer_ids = {
        tokenizer[token] for token in list_composer_tokens(tokenizer)
    }
    decode_ids = [token_id for token_id in token_ids if token_id not in composer_ids]
    sequence = TokSequence(ids=decode_ids)
    score = tokenizer.tokens_to_midi([sequence])
    score.dump_midi(output_path)
    logger.info("Saved generated MIDI to %s", output_path)


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    device = get_device()
    logger.info("Device: %s", device)

    tokenizer = ComposerREMI(params=str(TOKENIZER_PATH))
    logger.info("Loaded tokenizer from %s | vocab_size=%d", TOKENIZER_PATH, len(tokenizer))

    model = load_model(CHECKPOINT_PATH, device)
    if model.vocab_size != len(tokenizer):
        logger.warning(
            "Checkpoint vocab_size=%d != tokenizer vocab_size=%d; using the "
            "checkpoint value to stay consistent with the trained weights",
            model.vocab_size,
            len(tokenizer),
        )

    token_ids = generate(
        model,
        tokenizer,
        device,
        GENERATION_LENGTH,
        TEMPERATURE,
        TOP_K,
        composer=COMPOSER,
        top_p=TOP_P,
        cfg_scale=CFG_SCALE,
    )
    logger.info("Generated %d tokens", len(token_ids))

    tokens_to_midi_file(tokenizer, token_ids, OUTPUT_PATH)


if __name__ == "__main__":
    main()
