from __future__ import annotations

import logging
from pathlib import Path

import torch
import torch.nn.functional as F
from miditok import REMI, TokSequence
from torch import Tensor

from model import KVCache, MusicTransformer, get_device
from scripts.tokenize_midi import (
    UNCONDITIONAL_COMPOSER,
    ComposerREMI,
    composer_vocab_token,
    learned_token_id,
)

CHECKPOINT_PATH = Path("checkpoints/model_best.pt")
TOKENIZER_PATH = Path("data/processed/tokenizer.json")
OUTPUT_PATH = Path("data/processed/output.mid")

COMPOSER = "Frédéric Chopin"
GENERATION_LENGTH = 1024
TEMPERATURE = 0.9
# Min-P keeps every token whose probability is at least MIN_P times the top
# token's probability. The cutoff scales with model confidence, which trims the
# long tail without the fixed-mass distortion of nucleus sampling.
MIN_P = 0.05
CFG_SCALE = 2.0
# The training chunks never contained EOS, so its logit is unreliable early on.
MIN_NEW_TOKENS = 64

FORBIDDEN_PREFIXES = ("PAD", "BOS", "MASK", "Composer")

logger = logging.getLogger(__name__)


def iter_vocab_entries(tokenizer: REMI) -> list[tuple[int, list[str]]]:
    """(model id, constituent base tokens) for every id the model can emit.

    With a trained BPE model one id may decompose into several base tokens;
    without one every id maps to exactly one base token.
    """
    if tokenizer.is_trained:
        bytes_to_tokens = tokenizer._vocab_learned_bytes_to_tokens
        return [
            (int(token_id), list(bytes_to_tokens[byte_form]))
            for byte_form, token_id in tokenizer.vocab_model.items()
        ]
    return [(int(token_id), [token]) for token, token_id in tokenizer.vocab.items()]


class TokenCategories:
    def __init__(self, tokenizer: REMI, device: torch.device) -> None:
        forbidden: list[int] = []
        for token_id, base_tokens in iter_vocab_entries(tokenizer):
            prefixes = {token.split("_")[0] for token in base_tokens}
            if prefixes & set(FORBIDDEN_PREFIXES):
                forbidden.append(token_id)

        self.eos_token_id = learned_token_id(tokenizer, "EOS_None")
        self.forbidden_ids = torch.tensor(
            sorted(set(forbidden) - {self.eos_token_id}),
            dtype=torch.long,
            device=device,
        )


def load_model(checkpoint_path: Path, device: torch.device) -> MusicTransformer:
    checkpoint = torch.load(checkpoint_path, map_location=device)
    vocab_size = int(checkpoint["vocab_size"])
    model = MusicTransformer(vocab_size=vocab_size).to(device)
    state_dict = checkpoint["model_state_dict"]
    cleaned = {
        (key[len("_orig_mod.") :] if key.startswith("_orig_mod.") else key): value
        for key, value in state_dict.items()
    }

    try:
        model.load_state_dict(cleaned)
    except RuntimeError as exc:
        raise RuntimeError(
            f"Checkpoint {checkpoint_path} does not match the current architecture "
            "(RMSNorm + SwiGLU + KV-cache). Checkpoints trained before this change "
            "must be regenerated by re-running train.py."
        ) from exc
    model.eval()
    logger.info(
        "Loaded model from %s | vocab_size=%d | %.2fM params",
        checkpoint_path,
        vocab_size,
        model.get_num_params(),
    )
    return model


def list_composer_tokens(tokenizer: REMI) -> list[str]:
    return sorted(token for token in tokenizer.vocab if token.startswith("Composer_"))


def resolve_composer_token(tokenizer: REMI, composer: str) -> str:
    token = composer_vocab_token(composer)
    if token in tokenizer.vocab:
        return token

    available = list_composer_tokens(tokenizer)
    raise KeyError(
        f"Composer token {token!r} missing from tokenizer. Available: {available}"
    )


def pick_start_token(tokenizer: REMI, composer: str) -> int:
    token = resolve_composer_token(tokenizer, composer)
    start_token = learned_token_id(tokenizer, token)
    logger.info("Using composer seed %s (id=%d)", token, start_token)
    return start_token


def pick_unconditional_token(tokenizer: REMI) -> int | None:
    token = composer_vocab_token(UNCONDITIONAL_COMPOSER)
    if token not in tokenizer.vocab:
        return None
    return learned_token_id(tokenizer, token)


def min_p_filter(logits: Tensor, min_p: float) -> Tensor:
    assert logits.ndim == 1, f"Got {logits.shape}"
    if min_p <= 0.0:
        return logits

    probs = F.softmax(logits, dim=-1)
    threshold = min_p * probs.max()
    # The argmax always survives, so the filtered distribution is never empty.
    return logits.masked_fill(probs < threshold, float("-inf"))


@torch.no_grad()
def generate(
    model: MusicTransformer,
    tokenizer: REMI,
    device: torch.device,
    length: int,
    temperature: float = TEMPERATURE,
    composer: str = COMPOSER,
    min_p: float = MIN_P,
    cfg_scale: float = CFG_SCALE,
) -> list[int]:
    assert temperature > 0.0, f"Got temperature={temperature}"
    assert 0.0 <= min_p < 1.0, f"Got min_p={min_p}"

    categories = TokenCategories(tokenizer, device)
    start_token = pick_start_token(tokenizer, composer)

    uncond_token = pick_unconditional_token(tokenizer)
    if cfg_scale != 1.0 and uncond_token is None:
        logger.warning(
            "Tokenizer has no %s token, disabling classifier-free guidance. "
            "Re-run scripts/tokenize_midi.py to rebuild the vocabulary.",
            composer_vocab_token(UNCONDITIONAL_COMPOSER),
        )
        cfg_scale = 1.0
    use_cfg = cfg_scale != 1.0

    # The rotary cache is sized to max_seq_len, so generation cannot outrun it.
    max_tokens = min(length, model.max_seq_len)
    if max_tokens < length:
        logger.warning(
            "Requested %d tokens but max_seq_len=%d; truncating the request",
            length,
            model.max_seq_len,
        )

    batch_size = 2 if use_cfg else 1
    generated = torch.empty((batch_size, max_tokens), device=device, dtype=torch.long)
    generated[0, 0] = start_token
    if use_cfg:
        assert uncond_token is not None
        generated[1, 0] = uncond_token
        logger.info(
            "Classifier-free guidance scale=%.2f (uncond id=%d)",
            cfg_scale,
            uncond_token,
        )

    past_key_values: list[KVCache | None] | None = None
    log_every = max(max_tokens // 10, 1)
    total_tokens = max_tokens

    step = 1
    while step < max_tokens:
        # The cache is never trimmed: the first pass consumes the whole prefix and
        # every later pass feeds exactly one new token on top of the kept cache.
        context = generated[:, :step] if past_key_values is None else generated[:, step - 1 : step]

        logits, past_key_values = model(
            context,
            past_key_values=past_key_values,
            use_cache=True,
        )

        if use_cfg:
            conditional = logits[0, -1, :].float()
            unconditional = logits[1, -1, :].float()
            next_logits = unconditional + cfg_scale * (conditional - unconditional)
        else:
            next_logits = logits[0, -1, :].float()
        assert next_logits.ndim == 1, f"Got {next_logits.shape}"

        next_logits[categories.forbidden_ids] = float("-inf")
        if step < MIN_NEW_TOKENS:
            next_logits[categories.eos_token_id] = float("-inf")

        next_logits = min_p_filter(next_logits / temperature, min_p)
        probs = F.softmax(next_logits, dim=-1)
        next_token = int(torch.multinomial(probs, num_samples=1).item())

        if next_token == categories.eos_token_id:
            logger.info("EOS sampled at step %d, stopping", step)
            total_tokens = step
            break

        generated[:, step] = next_token
        step += 1

        if step % log_every == 0 or step == max_tokens:
            logger.info("Generated %d/%d tokens (id=%d)", step, max_tokens, next_token)

    result = generated[0, :total_tokens].tolist()
    assert len(result) == total_tokens, f"Got {len(result)}"
    return result


def tokens_to_midi_file(
    tokenizer: REMI,
    token_ids: list[int],
    output_path: Path,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    composer_ids = {
        learned_token_id(tokenizer, token)
        for token in list_composer_tokens(tokenizer)
    }
    eos_id = learned_token_id(tokenizer, "EOS_None")
    decode_ids = [
        token_id
        for token_id in token_ids
        if token_id not in composer_ids and token_id != eos_id
    ]
    sequence = TokSequence(ids=decode_ids, are_ids_encoded=tokenizer.is_trained)
    score = tokenizer.decode([sequence])
    score.dump_midi(output_path)
    logger.info("Saved generated MIDI to %s", output_path)


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    device = get_device()
    logger.info("Device: %s", device)

    tokenizer = ComposerREMI(params=str(TOKENIZER_PATH))
    logger.info(
        "Loaded tokenizer from %s | vocab_size=%d | bpe=%s",
        TOKENIZER_PATH,
        len(tokenizer),
        tokenizer.is_trained,
    )

    model = load_model(CHECKPOINT_PATH, device)
    if model.vocab_size != len(tokenizer):
        logger.warning(
            "Checkpoint vocab_size=%d != tokenizer vocab_size=%d; using the "
            "checkpoint value to stay consistent with the trained weights",
            model.vocab_size,
            len(tokenizer),
        )

    token_ids = generate(
        model,
        tokenizer,
        device,
        GENERATION_LENGTH,
        temperature=TEMPERATURE,
        composer=COMPOSER,
        min_p=MIN_P,
        cfg_scale=CFG_SCALE,
    )
    logger.info("Generated %d tokens", len(token_ids))

    tokens_to_midi_file(tokenizer, token_ids, OUTPUT_PATH)


if __name__ == "__main__":
    main()
