"""Autoregressive sampler: KV-cached decoding, CFG, min-p, repetition penalty."""
from __future__ import annotations

import logging
from pathlib import Path

import torch
import torch.nn.functional as F
from miditok import REMI, TokSequence
from torch import Tensor

from musiclm.config import (
    FORBIDDEN_PREFIXES,
    GRID_PREFIXES,
    PITCH_PREFIXES,
    GenerateConfig,
)
from musiclm.data.tokenizer import (
    UNCONDITIONAL_COMPOSER,
    ComposerREMI,
    composer_vocab_token,
    iter_vocab_entries,
    learned_token_id,
)
from musiclm.model import KVCache, MusicTransformer, get_device

logger = logging.getLogger(__name__)


class TokenCategories:
    def __init__(self, tokenizer: REMI, device: torch.device) -> None:
        forbidden: list[int] = []
        pitch: list[int] = []
        vocab_size = len(tokenizer)
        for token_id, base_tokens in iter_vocab_entries(tokenizer):
            prefixes = {token.split("_")[0] for token in base_tokens}
            if prefixes & set(FORBIDDEN_PREFIXES):
                forbidden.append(token_id)
            # A BPE id may merge several base tokens. It only counts as a pitch
            # token when it carries a pitch and no grid token, so penalizing it
            # can never suppress a Bar/Position the model needs to keep time.
            if prefixes & set(PITCH_PREFIXES) and not prefixes & set(GRID_PREFIXES):
                pitch.append(token_id)

        self.eos_token_id = learned_token_id(tokenizer, "EOS_None")
        self.forbidden_ids = torch.tensor(
            sorted(set(forbidden) - {self.eos_token_id}),
            dtype=torch.long,
            device=device,
        )
        self.is_pitch = torch.zeros(vocab_size, dtype=torch.bool, device=device)
        if pitch:
            self.is_pitch[torch.tensor(sorted(pitch), device=device)] = True
        logger.info(
            "Repetition penalty applies to %d/%d pitch-only ids",
            int(self.is_pitch.sum().item()),
            vocab_size,
        )


def load_model(checkpoint_path: Path, device: torch.device) -> MusicTransformer:
    checkpoint = torch.load(checkpoint_path, map_location=device)
    vocab_size = int(checkpoint["vocab_size"])
    model = MusicTransformer(vocab_size=vocab_size).to(device)
    state_dict = checkpoint["model_state_dict"]
    cleaned = {
        (key.removeprefix("_orig_mod.")): value
        for key, value in state_dict.items()
    }

    try:
        model.load_state_dict(cleaned)
    except RuntimeError as exc:
        raise RuntimeError(
            f"Checkpoint {checkpoint_path} does not match the current architecture "
            "(RMSNorm + SwiGLU + KV-cache). Checkpoints trained before this change "
            "must be regenerated by re-running train.py."
        ) from exc
    model.eval()
    logger.info(
        "Loaded model from %s | vocab_size=%d | %.2fM params",
        checkpoint_path,
        vocab_size,
        model.get_num_params(),
    )
    return model


def list_composer_tokens(tokenizer: REMI) -> list[str]:
    return sorted(token for token in tokenizer.vocab if token.startswith("Composer_"))


def resolve_composer_token(tokenizer: REMI, composer: str) -> str:
    token = composer_vocab_token(composer)
    if token in tokenizer.vocab:
        return token

    available = list_composer_tokens(tokenizer)
    raise KeyError(
        f"Composer token {token!r} missing from tokenizer. Available: {available}"
    )


def pick_start_token(tokenizer: REMI, composer: str) -> int:
    token = resolve_composer_token(tokenizer, composer)
    start_token = learned_token_id(tokenizer, token)
    logger.info("Using composer seed %s (id=%d)", token, start_token)
    return start_token


def pick_unconditional_token(tokenizer: REMI) -> int | None:
    token = composer_vocab_token(UNCONDITIONAL_COMPOSER)
    if token not in tokenizer.vocab:
        return None
    return learned_token_id(tokenizer, token)


def min_p_filter(logits: Tensor, min_p: float) -> Tensor:
    assert logits.ndim == 1, f"Got {logits.shape}"
    if min_p <= 0.0:
        return logits

    probs = F.softmax(logits, dim=-1)
    threshold = min_p * probs.max()
    # The argmax always survives, so the filtered distribution is never empty.
    return logits.masked_fill(probs < threshold, float("-inf"))


def apply_repetition_penalty(
    logits: Tensor,
    window: Tensor,
    penalty: float,
    is_penalizable: Tensor,
) -> Tensor:
    """Divide recently-used positive pitch logits, multiply negative ones.

    Scaling instead of subtracting keeps the penalty proportional to how much
    the model wants a token, so confident-but-repeated ids fall furthest.
    Structural, temporal and special ids are never touched: REMI reuses them on
    every note, so penalizing them would break the bar/beat grid.
    """
    assert logits.ndim == 1, f"Got {logits.shape}"
    assert is_penalizable.shape == logits.shape, (
        f"Got {is_penalizable.shape} vs {logits.shape}"
    )
    if penalty == 1.0 or window.numel() == 0:
        return logits

    seen = torch.unique(window)
    seen = seen[is_penalizable[seen]]
    if seen.numel() == 0:
        return logits

    scores = logits[seen]
    logits[seen] = torch.where(scores > 0, scores / penalty, scores * penalty)
    return logits


@torch.no_grad()
def generate(
    model: MusicTransformer,
    tokenizer: REMI,
    device: torch.device,
    length: int,
    temperature: float = 0.92,
    composer: str = "Frédéric Chopin",
    min_p: float = 0.02,
    cfg_scale: float = 1.2,
    repetition_penalty: float = 1.0,
    penalty_window: int = 64,
    min_new_tokens: int = 96,
    use_kv_cache: bool = True,
    seed: int | None = None,
) -> list[int]:
    assert temperature > 0.0, f"Got temperature={temperature}"
    assert 0.0 <= min_p < 1.0, f"Got min_p={min_p}"
    assert repetition_penalty >= 1.0, f"Got repetition_penalty={repetition_penalty}"
    assert penalty_window > 0, f"Got penalty_window={penalty_window}"

    if seed is not None:
        # Seeding the global generators keeps RNG consumption identical to the
        # unseeded code path, so seeded runs are reproducible bit-for-bit.
        torch.manual_seed(seed)

    categories = TokenCategories(tokenizer, device)
    start_token = pick_start_token(tokenizer, composer)

    uncond_token = pick_unconditional_token(tokenizer)
    if cfg_scale != 1.0 and uncond_token is None:
        logger.warning(
            "Tokenizer has no %s token, disabling classifier-free guidance. "
            "Re-run `musiclm-tokenize` to rebuild the vocabulary.",
            composer_vocab_token(UNCONDITIONAL_COMPOSER),
        )
        cfg_scale = 1.0
    use_cfg = cfg_scale != 1.0

    # The rotary cache is sized to max_seq_len, so generation cannot outrun it.
    max_tokens = min(length, model.max_seq_len)
    if max_tokens < length:
        logger.warning(
            "Requested %d tokens but max_seq_len=%d; truncating the request",
            length,
            model.max_seq_len,
        )

    batch_size = 2 if use_cfg else 1
    generated = torch.empty((batch_size, max_tokens), device=device, dtype=torch.long)
    generated[0, 0] = start_token
    if use_cfg:
        assert uncond_token is not None
        generated[1, 0] = uncond_token
        logger.info(
            "Classifier-free guidance scale=%.2f (uncond id=%d)",
            cfg_scale,
            uncond_token,
        )

    past_key_values: list[KVCache | None] | None = None
    log_every = max(max_tokens // 10, 1)
    total_tokens = max_tokens

    step = 1
    while step < max_tokens:
        if use_kv_cache:
            context = (
                generated[:, :step]
                if past_key_values is None
                else generated[:, step - 1 : step]
            )
            logits, past_key_values = model(
                context,
                past_key_values=past_key_values,
                use_cache=True,
            )
        else:
            logits, _ = model(generated[:, :step])

        if use_cfg:
            conditional = logits[0, -1, :].float()
            unconditional = logits[1, -1, :].float()
            next_logits = unconditional + cfg_scale * (conditional - unconditional)
        else:
            next_logits = logits[0, -1, :].float()
        assert next_logits.ndim == 1, f"Got {next_logits.shape}"

        next_logits[categories.forbidden_ids] = float("-inf")
        if step < min_new_tokens:
            next_logits[categories.eos_token_id] = float("-inf")

        next_logits = apply_repetition_penalty(
            next_logits,
            generated[0, max(0, step - penalty_window) : step],
            repetition_penalty,
            categories.is_pitch,
        )
        next_logits = min_p_filter(next_logits / temperature, min_p)
        probs = F.softmax(next_logits, dim=-1)
        # Kept on device: writing the sample straight into `generated` avoids a
        # host synchronization on every step of the loop.
        next_token = torch.multinomial(probs, num_samples=1)

        generated[:, step] = next_token
        step += 1

        # EOS and progress both need host-side values, so they are the only
        # places that synchronize, and only once EOS is actually reachable.
        if step > min_new_tokens and bool(next_token.eq(categories.eos_token_id)):
            logger.info("EOS sampled at step %d, stopping", step - 1)
            total_tokens = step - 1
            break

        if step % log_every == 0 or step == max_tokens:
            logger.info(
                "Generated %d/%d tokens (id=%d)",
                step,
                max_tokens,
                int(next_token.item()),
            )

    result = generated[0, :total_tokens].tolist()
    assert len(result) == total_tokens, f"Got {len(result)}"
    return result


def tokens_to_midi_file(
    tokenizer: REMI,
    token_ids: list[int],
    output_path: Path,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    composer_ids = {
        learned_token_id(tokenizer, token)
        for token in list_composer_tokens(tokenizer)
    }
    eos_id = learned_token_id(tokenizer, "EOS_None")
    decode_ids = [
        token_id
        for token_id in token_ids
        if token_id not in composer_ids and token_id != eos_id
    ]
    sequence = TokSequence(ids=decode_ids, are_ids_encoded=tokenizer.is_trained)
    score = tokenizer.decode([sequence])
    score.dump_midi(output_path)
    logger.info("Saved generated MIDI to %s", output_path)


def main(cfg: GenerateConfig | None = None) -> Path:
    """Generate one piece and save it as MIDI; returns the output path."""
    if cfg is None:
        cfg = GenerateConfig()
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    device = get_device()
    logger.info("Device: %s", device)

    tokenizer = ComposerREMI(params=str(cfg.tokenizer_path))
    logger.info(
        "Loaded tokenizer from %s | vocab_size=%d | bpe=%s",
        cfg.tokenizer_path,
        len(tokenizer),
        tokenizer.is_trained,
    )

    model = load_model(cfg.checkpoint_path, device)
    if model.vocab_size != len(tokenizer):
        logger.warning(
            "Checkpoint vocab_size=%d != tokenizer vocab_size=%d; using the "
            "checkpoint value to stay consistent with the trained weights",
            model.vocab_size,
            len(tokenizer),
        )

    token_ids = generate(
        model,
        tokenizer,
        device,
        cfg.length,
        temperature=cfg.temperature,
        composer=cfg.composer,
        min_p=cfg.min_p,
        cfg_scale=cfg.cfg_scale,
        repetition_penalty=cfg.repetition_penalty,
        penalty_window=cfg.penalty_window,
        min_new_tokens=cfg.min_new_tokens,
        use_kv_cache=cfg.use_kv_cache,
        seed=cfg.seed,
    )
    logger.info("Generated %d tokens", len(token_ids))

    tokens_to_midi_file(tokenizer, token_ids, cfg.output_path)
    return Path(cfg.output_path)


if __name__ == "__main__":
    main()
